In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

# --- Passo 1: Carregar e selecionar ---
houses_file_path = "/kaggle/input/datasets/rishitaverma02/house-prices-advanced-regression-techniques/train (1).csv"
houses_data = pd.read_csv(houses_file_path)

features_names = ["GrLivArea", "OverallQual", "YearBuilt"]
colunas = features_names + ["SalePrice"]

# --- Passo 2: Conferir e dividir ---
print("Ausências por coluna:")
print(houses_data[colunas].isnull().sum())

total_inicial = len(houses_data)
houses_data = houses_data.dropna(subset=colunas)
print(f"Linhas incompletas removidas: {total_inicial - len(houses_data)}")

X = houses_data[features_names]
y = houses_data["SalePrice"]

# Divisão: 60% Treino, 40% Resto
train_X, resto_X, train_y, resto_y = train_test_split(
    X, y, test_size=0.40, random_state=42
)

# 50% de 40% = 20% do total para validação e 20% para treino
teste_X, val_X, teste_y, val_y = train_test_split(
    resto_X, resto_y, test_size=0.50, random_state=42
)

# --- Passo 3: Treinar os modelos isolados ---
houses_model_linear = LinearRegression()
houses_model_random = RandomForestRegressor(
    n_estimators=100, min_samples_leaf=3, random_state=42
)

houses_model_linear.fit(train_X, train_y)
houses_model_random.fit(train_X, train_y)

Ausências por coluna:
GrLivArea      0
OverallQual    0
YearBuilt      0
SalePrice      0
dtype: int64
Linhas incompletas removidas: 0

RandomForestRegressor(min_samples_leaf=3, random_state=42)

In [2]:
# --- Passo 4: Previsões e Combinação (Média com pesos iguais) ---
predict_linear = houses_model_linear.predict(teste_X)
predict_random = houses_model_random.predict(teste_X)
print("Linear Regression: ")
print(predict_linear)
print("----------------------------------------")
print("\n\nRandom Forest Regressor: ")
print(predict_random)
print("----------------------------------------")

Linear Regression:
[160598.62565072 309285.27009641 283241.28559329 107024.06922434
 341996.1692925  286912.84488284 257850.29785766 158664.28311359
 224209.69888633 133927.05903    148293.4656553  132797.81889323
 165464.21121522 146131.29548574 197797.79009605 316780.49430839
 290575.52142207 211812.75170834 249120.74851355 322375.51289909
 152124.47349476 138562.70861746 126882.10369845 255063.6717983
 106687.04776628 136614.041712   209886.87783038 135126.52692294
 128121.87044858 162746.06603316 439795.28655502  82726.43783076
 126459.042908   208978.69092032 107131.8750287  129833.67255111
 307458.37450607  99536.28711602 120988.15497564  84105.93976988
 119036.76726118  84946.61973278 180713.80419184  91494.38473302
 292269.76506951 275323.00059087 232794.89093341 253098.68003886
 122090.70030021 214391.41530822 266216.1309315  212304.34600148
 120108.87040902 135007.63083702 244517.2353563  171669.66755959
 171156.15237429 181588.52188399 164344.31448115 149616.75797439
 231528.63641665 212514.5159922  190744.6723375  141656.42723591
 190887.84865882 116400.45339461 194402.42053649 183262.74593832
 117925.0329541   94490.87455092 168218.18756662 146954.20994798
 197902.87509141 449395.444761   335104.76024049 142276.77429544
 115012.06870516 117831.85775025 171865.56580738 116688.50029073
 147452.94011259 304351.66430699 166754.4397352  212721.45189617
 157282.36659766 159543.05440245 120777.47170716 199420.83205719
 189605.06224249 218244.54847723 164827.74634729  83507.77327349
 148384.64037349 150316.26210163 190543.17805153 122028.12169328
 194410.58296348  91817.8021461  205169.39692744 120939.18041369
 238019.47147353 134333.28168871 165695.63440016 132027.57373207
 104174.65751247 182355.07230602 216678.64350502 124197.32854769
 205041.0582522  280608.92613682  91355.62347417 113342.77299107
 192124.89459995 136191.70124489  98574.40434935 175103.1810705
 301016.35959094 202850.03230043 144095.66187899 242285.96317271
 275274.53930669 222513.76098542  99121.08252038 100757.21524875
 133846.46131561 174271.63746473 165576.94535981 273821.88175683
 246430.53174479 146694.39769736 202502.18023176 186840.3570753
 127649.83509619 118737.32385132 234993.20717685 201551.43430788
  90122.01866537 112472.47036139 225327.08185699 251867.07571571
 340476.72511882 127146.17659135  50758.36866029 153780.37220945
 194618.03214521 291214.19382123 195663.44048083 203264.98328927
 241635.68721422 109407.86113195 234143.90413458 268965.17894267
 182996.77174637 182866.68619227 113306.42854397 164692.93949854
 330355.86323068 115610.44224713 127568.72410404 156787.33117219
 245543.39098337 182170.66975859 273947.49962307 266294.00783689
 149551.97183622 222613.40436278 224968.80720471 191695.05940381
 131369.64862435 126170.48273412 275701.04122947 139497.79738531
 122515.96862189 190684.50830738 114004.75169549 184303.01888814
  81167.97496221 121739.5615194  183670.96908268 188424.64001254
 271306.9777396   85470.35045612 218408.97799277 134358.28224744
 248164.1003193  131668.57875645 231488.33755945 119397.76272246
 224507.9086951  306590.12498743 156794.51966904 207790.10626337
 205172.32478201  10158.39303742  82060.86357381 147325.11471511
  83179.2204746  269126.8876492  148675.92135636 219646.0239339
 244460.61164512 251988.48556506 160455.4493294  274037.49336555
 224866.44301834 295102.64488182 116173.9585499  305609.70983555
 294833.13037092 141307.34156615 154508.11098218  78716.67610743
 121974.73206886 238083.53728836 258508.0159198  177002.15309067
 200717.2225185  112079.85174767 140813.2335096  222597.0795088
 185184.510986   218516.78379713 213234.29938352 143088.34486932
  98632.51526843 149073.26126474 209689.79860688  79473.218037
 205846.8809759  188688.71290544 211816.49907286 210727.55779328
 156785.84396429 288876.60304119 123437.75957694 168312.38932599
 184550.76692707 298255.70802045 252255.27926696 149163.76828498
 121233.18220557 250961.60961465 220831.88778186 211816.49907286
  95689.8291661  167496.19664407 156706.7334578  215123.6217688
 322163.34242271 279159.24300276 219427.69151619 192052.45931256
 149991.30485526 132738.98765081 238382.46742046 255396.73884626
 224281.67352136 132116.12682787 175308.88337336 371748.57081003
 103619.81691445 248227.65285637 212905.44035245 158122.53328279
 235420.52860958 136360.33877732 249457.76997161 211364.27626801
 168424.61019282 229780.48986703 228806.79649546 103805.19339202
 259442.89764208 254136.43922526 150257.43085921 173931.89519767
 208459.16821388 221961.12791863 251811.93921243 135862.12189048
 206226.4088224  270301.86826117 140239.65348078 185764.04591057
 229649.68398959 157282.36659766 160716.80141331 134172.59953769
 149802.44068414 324906.94881588 227898.60958539 241389.63342877]
----------------------------------------


Random Forest Regressor:
[162488.20820851 397398.47029385 262020.3049738  117949.59981962
 412105.47990873 349159.8616468  230108.14920635 145111.11129149
 212332.12285256 139537.65097403 150890.69297835 144868.53686869
 144868.6297619  134448.76776407 190256.5359127  413788.00865043
 367368.42112934 207705.58106746 258239.0684127  394100.19455159
 140522.99069264 145545.47705628 145988.48757215 325754.56059235
 118101.18363165 137254.1459596  185111.98238997 150037.20344517
 143781.90355339 142067.86071429 438529.9704932   89025.13423521
 144359.03225108 191949.26239286 117949.59981962 148674.29072872
 454626.761136   121651.66407759 135356.51121934 104502.89981962
 124229.53353175 103526.4525974  175498.99793912 109551.7150974
 295421.81526876 291457.94139497 227983.29365079 267229.71903896
 133015.19243923 239220.18167641 279767.90066558 186226.87825938
 127791.62851732 163904.94432215 263803.34647253 179694.43041126
 158195.24887807 164226.08244811 171744.65215063 128002.72713564
 227888.48910198 181787.13762987 185934.41630952 148606.72195887
 177910.64090632 120772.85575397 190596.87420635 150197.26510678
 110326.96754912 100505.96152597 172312.39705087 132104.63519536
 188062.15190476 439201.17715987 412825.2502381  121943.01208181
 120836.95770202 125844.95465673 167024.98493939 121130.91359335
 134427.64087302 325646.09341811 162405.61917424 188118.37272894
 139984.39412809 144737.94671717 135493.67436869 186186.59007937
 182423.34323232 209960.95920238 158348.06907648  92294.444886
 149164.15822511 171167.96346986 170704.02648882 131540.15137085
 176182.94489899 109551.7150974  201619.00137987 135433.70770202
 207058.80738636 169730.3182583  156873.0412987  122369.72243867
 119939.90836941 159356.25299134 192584.11787698 115944.68443223
 177887.78415476 333512.32441772 109253.75676407 126439.29740332
 186930.66529304 122155.05405101 111617.01272616 150008.31269086
 387446.31024603 224091.69096764 150749.06441919 281282.20900144
 322119.9547732  227434.53969444 115800.54143218 110172.404329
 137715.74615801 165071.17574206 160702.28607143 326393.64136844
 224620.60125397 143938.6722069  171964.87573485 171453.32072206
 122700.54288281 125616.50440115 251356.92003968 211724.61668193
  92321.58344156 145018.9985938  226805.18753644 263053.04824242
 409234.07441414 137463.99776196  77148.05425685 154201.5395202
 190311.69563492 359353.39796753 192892.49295094 193145.60185714
 212184.83183225 114945.89989255 215022.58764719 306151.78463889
 176583.03858874 171703.76504052  92390.20904928 143460.47194905
 404202.48814683 119830.93786075 125675.30983045 145087.83559149
 255120.18445527 180966.38728175 303624.38444048 288179.39548196
 132877.53306277 216119.46114591 188624.0565812  169325.74336291
 144616.59199134 136826.9362013  309551.22089899 109359.75693606
 133578.23152958 169178.99531746 123996.91857864 176112.33524531
 106690.43870851 130958.06968795 171192.03761905 178542.31209343
 287711.91173737 105014.97400794 227762.70697222 139142.11309524
 271429.35875375 142124.804329   218476.72106854 125209.22672022
 173438.99747763 395930.93172242 139432.19135032 182613.50259921
 208884.53813908  69014.89289322  96080.88582251 125915.41913586
  92617.93813131 314089.53924603 101875.43226912 229525.55930556
 261529.09647253 302464.57016667 147888.68333622 326393.64136844
 183980.77690587 304702.53947222 116092.06954365 333339.52185567
 305074.68280556 150895.01977345 161093.65859654  90669.96210317
 136322.35415584 235639.54458297 239534.02910317 173307.86852778
 188856.24053724 111829.78661616 115536.68430403 186736.74840659
 185127.88788684 228074.18447222 197105.75541378 145192.54208874
 115035.85135642 152019.6077417  179867.03968254  89042.83156854
 169804.79162374 185949.30763889 182689.4262013  179571.66179654
 145013.12637085 301856.53843146 134586.37914863 162015.29655067
 164426.89033189 321627.70936291 246717.5657096  100841.66044372
 124663.96503191 244332.92868579 203675.78123321 182689.4262013
 106948.36057143 157554.97130952 164950.4107518  209950.07134921
 397412.39550813 279754.13849206 223524.41309524 173289.02490548
 129350.34474803 149798.65193001 220219.21862299 264823.90683261
 205656.56424908 140779.31718975 173353.02680375 398705.36859271
 104770.77237623 246550.10882756 182111.75571429 144330.65479798
 213472.70360495 137694.58451715 274638.18213722 180215.39354509
 172863.95263348 258150.87927417 171035.20821104 114872.2594246
 270225.97456277 279049.64115909 149040.29391306 163154.84144733
 216231.8665232  205710.88412698 250037.68554293 138949.56231962
 179831.2328824  269488.98969192 143298.50265945 155399.35411255
 209876.20025397 139984.39412809 172515.71189322 135503.28742785
 150067.72849928 383406.75632198 210914.87120208 233766.34068914]
----------------------------------------

In [3]:
# Combinação direta dos dois vetores
houses_mean = (predict_linear + predict_random) / 2

# --- Passo 5: Comparar com a tabela de MAE (em dólares) ---
mae_linear = mean_absolute_error(val_y, predict_linear)
mae_random = mean_absolute_error(val_y, predict_random)
mae_combinado = mean_absolute_error(val_y, houses_mean)

tabela_comparativa = pd.DataFrame({
    "Modelo": ["Linear", "Floresta", "Média dos dois"],
    "MAE (USD)": [mae_linear, mae_random, mae_combinado]
})

display(tabela_comparativa)

           Modelo     MAE (USD)
0          Linear  77669.044912
1        Floresta  80592.072058
2  Média dos dois  78703.879080

In [4]:
#Avaliação final: retreine a opção escolhida com treino e validação juntos. Avalie uma vez no teste.
houses_test_path = "/kaggle/input/datasets/rishitaverma02/house-prices-advanced-regression-techniques/test (1).csv"
houses_test_data = pd.read_csv(houses_test_path)

features_names_test = ["GrLivArea", "OverallQual", "YearBuilt"]

test_X = houses_test_data[features_names_test]

#Para a combinação, retreine ambos e faça a média das previsões.
houses_model_linear.fit(resto_X, resto_y)
houses_model_random.fit(resto_X, resto_y)

predicts_linear = houses_model_linear.predict(test_X)
predicts_random = houses_model_random.predict(test_X)

houses_mean_test = (predicts_linear + predicts_random) / 2

mean_linear = sum(predicts_linear) /  len(predicts_linear)
mean_random = sum(predicts_random) / len(predicts_random)
mean_combinado = sum(houses_mean_test) / len(houses_mean_test)

tabela_comparativa_test = pd.DataFrame({
    "Modelo": ["Linear", "Floresta", "Valores"],
    "MAE (USD)": [mean_linear, mean_random, mean_combinado]
})

display(tabela_comparativa_test)

     Modelo      MAE (USD)
0    Linear  180155.545182
1  Floresta  179795.373347
2   Valores  179975.459265

### Como cada algoritmo funciona e como vocês uniram as previsões?
O algoritmo de regressão linear combina as colunas "GrLivArea", "OverallQual" e "YearBuilt" aplica pesos aprendidos a cada um para estimar um valor contínuo numérico (preço). Ela busca a relação linear que minimiza a soma dos erros quadráticos.
O algoritmo Random Forest é um conjunto de árvores de decisão, que cria 100 árvores diversificadas e estima o preço dos imóveis combinando as características (área, qualidade e idade
A união das previsões foi feita por média aritmética simples. "houses_mean = (predict_linear + predict_random) / 2"

### Qual modelo isolado teve menor MAE na validação? Informe os dois valores.
foi o de Regressão Linear: 77669.044912 USD

Random Forest: 80592.072058 USD

### A média melhorou, piorou ou empatou com o melhor modelo isolado? Informe a diferença em dólares.
A média das previsões piorou o resultado em comparação com o melhor modelo isolado, ela errou 1034.834168 USD a mais do que a Regressão Linear sozinha (78703.879080 - 77669.044912 = 1034.834168 USD)
### Qual opção foi escolhida e qual foi seu MAE no teste final?
Foi escolhido o algoritmo de regressão linear e o MAE no teste final: 180.155,545182.